### ISSUE TITLE
Rename Working System to Windowing System

### ISSUE THREAD

**Issue by PhilMFischer** [DLR-SC/Overtarget#21]
The Key Word Working System in the tmodel language is not correct:

![grafik](https://user-images.githubusercontent.com/35496033/63956529-e2bd5c80-ca86-11e9-8217-efb6507c9aab.png)

It should be called Windowing System as shown here:

![grafik](https://user-images.githubusercontent.com/35496033/63956403-a38f0b80-ca86-11e9-9ebf-da56d2d2da13.png)

⚠️ Assure Backwards compatibility for easy transition. Throw a warning if working system is used and advise users to use windowing system instead. Nevertheless the Keyword Working System should not stop working.

**Comment by Anna-Lena-DLR** [comment]
closed by #50
