### ISSUE TITLE
Edit Quick Fix "Create reposLoc for referencedTarget"

### ISSUE THREAD

**Issue by Anna-Lena-DLR** [DLR-SC/Overtarget#93]
When creating a target with an unresolved reference we have the wuick fix "Generate reference target". Before that we should offer a quick fix which creates a reposLoc with placeholders for the referencedTarget

**Comment by franzTobiasDLR** [comment]
![image](https://user-images.githubusercontent.com/49645871/79484196-9756bf00-8013-11ea-8f75-a719e43c2a73.png)
